version: "3.8"



services:

  postgres:

    image: postgres:latest  

    restart: always

    volumes:

      - postgres-data:/var/lib/postgresql/data

    environment:

      POSTGRES_USER: postgres

      POSTGRES_PASSWORD: mysecretpassword

      POSTGRES_DB: postgres-ultralims



volumes:

  postgres-data:
